volumes:
  n8n_storage:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  environment:
    - N8N_DIAGNOSTICS_ENABLED=false

services:
  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials &&
        n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared
    depends_on:
      n8n-import:
        condition: service_completed_successfully
